# Generated by Django 5.1.1 on 2024-10-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hoteluser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteluser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
