# Generated by Django 5.1.1 on 2024-10-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_hoteluser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelvendor',
            name='business_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
