# Generated by Django 5.1.1 on 2024-10-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_hotelbooking_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='booding_end_date',
            new_name='booking_end_date',
        ),
    ]
